### ISSUE TITLE
Build issue on a fresh Xubuntu install

### ISSUE THREAD

**Issue by hpretl** [StefanSchippers/xschem-gaw#7]
When trying to build on Xubuntu, the following error shows up. Using the same procedure on an older machine works, but I have no idea what goes wrong.

```
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.20 but the autoconf macros are from gettext version 0.19
```

Any idea how to fix this? This happens on Xubuntu 20.04LTS, not on 21.10

**Comment by saul-rodriguez** [comment]
Same issue here Ubuntu 18.04, maybe time to upgrade :(

**Comment by StefanSchippers** [comment]
Saul, hpretl, please try to change po/Makefile.in.in, change the line:
GETTEXT_MACRO_VERSION = 0.20
and put 0.19 or 0.18, depending on the gettext version installed on your system, then do the usual configure rebuild and install:
```
aclocal && automake --add-missing && autoconf
./configure
make
sudo make install
````
The problem is this version number is hard coded so either new linux systems have problems or older linux systems have problems. I am not an autotools expert so i don't know how to fix this and automatically detect the installed version. This is what autotools should be supposed to do.
